FROM php:7.4.4-apache

ARG CERT_URL

ENV PROJECT_DIR=/var/www/html \
    APP_URL=localhost \
    VENDOR_DIR=/var/www/vendor \
    DATA_DIR=/var/www/data

#
# Install basic requirements
#
RUN apt-get update \
 && apt-get install -y \
 curl \
 apt-transport-https \
 git \
 vim \
 build-essential \
 libssl-dev \
 wget \
 unzip \
 bzip2 \
 libbz2-dev \
 zlib1g-dev \
# libfontconfig \
# libfreetype6-dev \
# libjpeg62-turbo-dev \
# libpng-dev \
# libicu-dev \
# libxml2-dev \
# libldap2-dev \
 libmcrypt-dev \
 python-pip \
# fabric \
# jq \
# gnupg \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install mysqli gettext gd

COPY ./src $PROJECT_DIR
COPY ./vendor $VENDOR_DIR
COPY ./data $DATA_DIR

# Adding Certs
RUN if [ -n "$CERT_URL" ]; then  curl -sL $CERT_URL | bash -; fi

COPY docker-entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh

VOLUME $PROJECT_DIR/storage

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["run"]
