name: Release

on:
  push:
    branches:
      - master

jobs:
  publish_docker_image:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Environment
      run: cp .sample.env .env
    - name: Build
      run: docker-compose build
      env:
        APP_HOST: localhost
        DB_USERNAME: user
        DB_PASSWORD: password
        DB_NAME: masstestingplatform
    - name: Build and Push Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adzuci/masstestingplatform
        path: .
        dockerfile: ./Dockerfile-prod
        tag_with_ref: true
        tag_with_sha: true