name: Jekyll site CI

on:
  push:
    branches: 
    - master
    paths:
    - 'docs/**'

jobs:
  # github-pages:
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: helaili/jekyll-action@2.0.1
  #       env:
  #         JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
  #         INPUT_GEM_SRC: 'docs'
  #       with:
  #         entrypoint: docs/entrypoint.sh
